/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6D1Wssdh1GFhg18GVMKyCt

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsthCzXqqSd9Ml } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: thCzXQQSd9Ml/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsthCzXqqSd9Ml
});
